package net.jsrois.libritos.book

import org.springframework.stereotype.Repository

@Repository
class BookRepository {
    companion object {
        private val books: MutableList<Book> = mutableListOf(
                Book("The Communist Manifesto", "Karl Marx, Friedrich Engels"),
                Book("A Dónde Va el Capitalismo Español", "Pedro Ramiro, Erika González"),
                Book("Historical Capitalism","Immanuel Wallerstein"),
                Book("Abolish Silicon Valley","Wendy Liu"),
                Book("The Rise of Neoliberal Feminism","Catherine Rottenberg"),
                Book("Dangerous Liaisons - the marriages and divorces of Marxism and Feminism","Cinzia Aruzzo"),
                Book("Tocar Fondo","Manuel Gabarre"),
                Book("La farsa de las startups: la cara oculta del mito emprendedor", "Javier López Menacho"),
                Book("De la especulación al derecho a la vivienda", "Raquel Rodríguez, Mario Espinoza"),
                Book("The Origin of Capitalism","Ellen M. Wood"),
                Book("Breve Historia del Neoliberalismo","David Harvey"),
                Book("La vaga de la canadenca","Ferrán Aisa"),
                Book("Estrategias contra la gentrificación","Lisa Vollmer"),
                Book("Out of the Wreckage","George Monbiot"),
                Book("Feminism for the 99%","Nancy Fraser"),
                Book("The ABCs of Socialism","Jacobin"),
                Book("In Defense of Housing: The Politics of Crisis","David Madden and Peter Marcuse"),
                Book("Hope in the Dark","Rebecca Solnit"),
                Book("Marx: The alternative to Capitalism","Kieran Allen"),
                Book("Fighting Fascism", "Clara Zetkin"),
                Book("Socialism...Seriously","Danny Katch"),
                Book("Propaganda Blitz", "David Cromwell,David Edwards"),
                Book("Papel Mojado","Mongolia"),
                Book("History of the Russian Revolution","Leon Trotsky",false),
                Book("The Mother of All Questions","Rebecca Solnit",false),
                Book("No Is Not Enough","Naomi Klein",false),
                Book("A People's History of the Russian Revolution","Neil Faulkner",false),
                Book("Memorias de un Ingeniero","Alfredo Hoces",false),
                Book("Soldiers in Revolt: GI Resistance During the Vietnam War","David Cortright",false),
                Book("Algiers, Third World Capital","Elaine Mokhtefi",false),
                Book("Woman Hating","Andrea Dworkin",false),
                Book("The Unwomanly Face of War","Svetlana Alexievich",false),
                Book("Mindstorms","Seymour Pappet",false),
                Book("The problems of philosophy","Bertrand Russel",false),
                Book("McMindfulness","Ronald Purser",false),
                Book("Los conceptos elementales del materialismo histórico","Marta Harnecker",false),
                Book("Why Nations Fail: The Origins of Power, Prosperity and Poverty","Daron Acemoglu, James A. Robinson",false),
                Book("The Alchemists: Three Central Bankers and a World on Fire","Neil Irwin",false),
                Book("Al menos tienes trabajo","Naiara Puertas",false),
                Book("Alta cultura descafeinada","Alberto Santamaría",false),
                Book("Adios Chueca","Shangay Lily",false),
                Book("An Introduction to Marxist Economic Theory","Ernest Mandel",false),
                Book("Why not default", "Jerome Roos",false),
                Book("La lucha por barcelona","chris ealham",false),
                Book("The Meritocracy Trap: How America's Foundational Myth Feeds Inequality, Dismantles the Middle Class, and Devours the Elite","Daniel Markovits",false),
                Book("Marx at the Arcade. Consoles, Controllers, and Class Struggle","Jamie Woodcock",false),
                Book("Bullshit Jobs","David Graeber",false),
                Book("Stolen: How to save the world from financialisation","Grace Blakeley",false),
                Book("Ecofascismo. Lecciones sobre la experiencia alemana", "Janet Biehl",false),
                Book("Creadores de hits. Cómo triunfar en la era de la distracción","Derek Thompson",false),
                Book("Growth","Vaclav Smil",false),
                Book("Historia de la CNT","Julian Vadillo",false),
                Book("Farewell to Growth","Serge Latouche",false),
                Book("Marx, Engels y la Revolución de 1848","Fernando Claudín",false),
                Book("La insurrección que viene","Comité invisible",false),
                Book("Daniel Bensaid","Una Lenta Impaciencia",false),
                Book("El Eco de los Pasos","García Oliver",false),
                Book("After the Gig","Juliet Schor",false),
                Book("Revolution and the State Anarchism in the Spanish Civil War, 1936–1939","Danny Evans",false),
                Book("El gran capital con hitler","Jacques Pauwels",false),
                Book("Reivindicando El Capital de Marx","Andrew Kliman",false),
                Book("Gestación Subrogada","Layla Martinez",false),
                Book("Playing Changes","Nate Chinen, Ron Butler",false),
                Book("Beneficios sin producción","Costas Lapavitsas",false),
                Book("Against Meritocracy","Jo Littler",false),
                Book("Flow","Mihaly Csikszentmihalyi" ,false),
                Book("The production of Money","Ann Pettifor",false),
                Book("teach yourself Postmodernism","Glenn Ward",false),
                Book("The Mythology of Work","Peter Fleming",false),
                Book("Economics for everyone", "Jim Stanford",false),
                Book("To save everything click here","Evgeni Morozov",false),
                Book("Despertar del sueño tecnológico","Ekaiz Cancela",false),
                Book("A Guerra dos Lugares","Raquel Rolnik",false),
                Book("La gran transformacion","Karl Polanyi",false),
                Book("El Jazz de la física","Stephon Alexander",false),
                Book("Salvador Allende","Victor Figueroa Clark",false),
                Book("A People’s History of the German Revolution","William A. Pelz",false),
                Book("Constructing China","Mobo Gao",false),
                Book("Accelerate","Nicole Forsgren",false),
                Book("A Radical History of the World","Neil Faulkner",false),
                Book("Men Explain Things to Me","Rebecca Solnit",false),
                Book("Capitalism","Arundhati Roy",false),
                Book("La Trampa de la Diversidad","Daniel Bernabé",false),
                Book("On Antisemitism","Jewish Voice for Peace",false),
                Book("In Defense of Degrowth","Giorgos Kallis",false),
                Book("The Revolutionary Ideas of Karl Marx", "Alex Callinicos",false),
                Book("The Washington Connection and Third World Fascism","Noam Chomsky and Edward S. Herman",false),
                Book("Assembly","Michael Hardt and Antonio Negri",false),
                Book("Women and Socialism","Sharon Smith",false),
                Book("Capital in the 21st century","Piketti",false),
                Book("Capital city","Samuel M. Stein", false),
                Book("The Square and the Tower: Networks and Power from the Freemasons to Facebook","Niall Ferguson",false),
                Book("Globalists","Quinn Slobodian",false),
                Book("El laberinto español", "Gerald Brennan",false),
                Book("How to Lie with Statistics","Darrell Huff",false),
                Book("Política para una izquierda racional","Eric J. Hobsbawm",false),
                Book("The Nazis, Capitalism and the Working Class","Donny Gluckstein",false),
                Book("No Logo","Naomi Klein",false),
                Book("The Boy who could change the world","various authors",false),
                Book("The Civic Foundations of Fascism in Europe","Dylan Riley",false),
                Book("A room of one's own","Virginia Woolf",false),
                Book("Developer Hegemony","Erik Dietrich",false),
                Book("Manufacturing Consent","Noam Chomsky",false),
                Book("Iglesia S.A.","Ángel Munárriz",false),
                Book("Capitalism: what it is and how can we destroy it", "various",false),
                Book("Octubre","China Melville",false)
        )
    }

    fun findAll(): List<Book> = books

    fun add(book: Book) {
        books.add(book)
    }
}
